import { AuthProvider } from "./Providers";

import "./globals.css";
import { Teko } from "next/font/google";

const teko = Teko({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "FOOTBALL NEWS APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${teko.className} min-h-screen bg-gray-100`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
